---
title: "STAT331 Project"
author: "Cassidy Gertzfield, Brandon Montalvo, Lauren Hu, Rapha Coutin"
format:
  html:
    embed-resources: true
    code-tools:       true
    toc:              true
    code-fold:        true
editor: source
execute:
  error:   true
  echo:    true
  message: false
  warning: false
---

```{r importdata}
# import data sets
library(readr)
library(tidyverse)


happy <- read_csv("hapiscore_whr.csv")
income <- read_csv("mincpcap_cppp.csv")
```

```{r pivot}
## make long data set 
happy <- happy|>
  pivot_longer(cols = `2005`:`2023`,
               names_to = "year",
               values_to = "happy_score")

income <- income|>
  pivot_longer(cols = `1800`:`2100`,
               names_to = "year",
               values_to = "avg_daily_inc")
```

```{r merge}
## merge into one data set 
happy_income <- happy|>
  left_join(income, 
            by = c("year","country"))
```

```{r NAs}
## deal with missing values 
happy_income <- happy_income|>
  filter(!is.na(happy_score) & !is.na(avg_daily_inc))
```
